# Travis configuration file
# Environment and script configuration copied from Jekyll Continuous Integration Guide (see https://jekyllrb.com/docs/continuous-integration/)
language: ruby
rvm:
  - 2.3.0

install: bundle install
script: jekyll build && htmlproofer ./_site --assume-extension

# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages     # test the gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-"